apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/steoli-platform-labs/helm-charts.git
    targetRevision: main
    path: charts/sample-api
    helm:
      releaseName: sample-api
      values: |
        image:
          repository: ghcr.io/steoli-platform-labs/sample-api
          tag: 1.0.0
        environment: dev
        replicaCount: 2
        autoscaling:
          minReplicas: 2
          maxReplicas: 5
        secret:
          enabled: true
          remoteKey: platform-labs/sample-api-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-api-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
